export default {
  ArthurAndMarina: "Дорогие Артур и Марина",
  NikitaAndJulia: "Дорогие Никита и Юлия",
  RinatAndElizabeth: "Дорогие Ринат и Елизавета",
  DenisAndKsenia: "Дорогие Денис и Ксения",
  Valery: "Дорогой Валерий",
  Brother: "Дорогой Брат",
  Alexei: "Дорогой Алексей",
  Aziza: "Дорогая Азиза",
  TatianaAndMaxim: "Дорогие Татьяна и Максим",
  ElenaAndAlexander: "Дорогие Елена и Александр",
  IliaAndMaria: "Дорогие Илья и Мария",
  AnnaAndPaul: "Дорогие Анна и Павел",
  PaulineAndDenis: "Дорогие Полина и Денис",
  ElenaAndIlia: "Дорогие Елена и Илья",
  DariaAndVladimir: "Дорогие Дарья и Владимир",
  MarinaAndSalavat: "Дорогие Марина и Салават",
  Sonya: "Дорогая Соня",
  Irina: "Дорогая Ирина",
  Daria: "Дорогая Дарья",
  ValeryAndAnna: "Дорогие Валерий и Анна",
};
