export default {
  ArthurAndMarina: "Дорогие<br/>Артур и Марина",
  NikitaAndJulia: "Дорогие<br/>Никита и Юлия",
  RinatAndElizabeth: "Дорогие<br/>Ринат и Елизавета",
  DenisAndKsenia: "Дорогие<br/>Денис и Ксения",
  Valery: "Дорогой Валерий",
  Brother: "Дорогой Брат",
  Alexei: "Дорогой Алексей",
  Aziza: "Дорогая Азиза",
  TatianaAndMaxim: "Дорогие<br/>Татьяна и Максим",
  ElenaAndAlexander: "Дорогие<br/>Елена и Александр",
  IliaAndMaria: "Дорогие<br/>Илья и Мария",
  AnnaAndPaul: "Дорогие<br/>Анна и Павел",
  PaulineAndDenis: "Дорогие<br/>Полина и Денис",
  ElenaAndIlia: "Дорогие<br/>Елена и Илья",
  DariaAndVladimir: "Дорогие<br/>Дарья и Владимир",
  MarinaAndSalavat: "Дорогие<br/>Марина и Салават",
  Sonya: "Дорогая Соня",
  Irina: "Дорогая Ирина",
  Daria: "Дорогая Дарья",
  ValeryAndAnna: "Дорогие<br/>Валерий и Анна",
};
